### ISSUE TITLE
Feature Request: Scratch Project Versioning

### ISSUE THREAD

**Issue by BoltBait** [griffpatch/Scratch3-Dev-Tools#17]
Do you have an integrated solution for version control for Scratch projects?

**Comment by ThatXliner** [comment]
Like git for scratch?

**Comment by griffpatch** [comment]
Sorry - I don't have any hooks into the scratch api to do anything with the
project as a whole

**Comment by BoltBait** [comment]
> Sorry - I don't have any hooks into the scratch api to do anything with the project as a whole

Bummer.

**Comment by Explosion-Scratch** [comment]
I just thought of something, would it be possible to implement this but only by changing a version numbering system in the title of the project? E.g. if a user titles a project with "v0.4.3" in the title than updating the project could change that to "v0.4.4"? This could work a few ways, through an "update version" button somewhere near the share button and see project page button (there's plenty of space there), or just automatically. Some sort of recognition system for version numbers would have to be made though.

**Comment by griffpatch** [comment]
These are all good ideas but should really be change requests against the
main scratch repo not my extension

**Comment by Explosion-Scratch** [comment]
Ah, I guess so.
