### ISSUE TITLE
Clicking cancel for share confirmation still shares the project.

### ISSUE THREAD

**Issue by Explosion-Scratch** [griffpatch/Scratch3-Dev-Tools#21]
Title. This happened on Firefox. I have not tried other browsers. To repro, click share with the extension enabled and then click cancel. The project will still share.

**Comment by griffpatch** [comment]
Oh bummer! Perhaps Firefox do not allow the cancelling of the prompt
bubbling :(. There may be nothing I can do about it...

**Comment by Explosion-Scratch** [comment]
***sigh* Oh well :( Thanks for looking though! I really love this extension btw!

**Comment by griffpatch** [comment]
Hey thanks :) - It's an attempt to make scratch do things that I'd have it
do if I had things just as I wanted them ;) - Except, I'm at the mercy of
doing it through the small backdoors left open to us in scratch at
present... they may not stay open forever, or they might change... I'd love
to do more, but I feel the scratch team may be clamping down on expentions
a bit more recently. I'd hate to lose these features!

**Comment by Explosion-Scratch** [comment]
No problem! I'm excited to see more developments in this, also I thought I might mention that Maximouse (mxmou on github), World_Languages and I are working on creating a browser extension with many userscripts, userstyles and addons in it. We are currently working on adding this extension to the project as well as a few others. The project is here: github.com/scratchaddons/extension
