### ISSUE TITLE
Search bar glitch ( needs fixing )

### ISSUE THREAD

**Issue by Akash-Karthik** [griffpatch/Scratch3-Dev-Tools#27]
<h2>Hi Griffpatch ,</h2>
<h3>Looks like your search bar sometimes dissapears . I have seen many people writing this in the reviews . I think this needs fixing . 
<p> I know some HTML :p<p>
And yes your extension has been copied . #25

**Comment by Akash-Karthik** [comment]
I will close this issue once it is fixed

**Comment by scratchusernamemrtbts** [comment]
I found this issue too
i think that is made of JavaScript not HTML
เมื่อ 10 ก.ย. 2020 6:04 เขียนโดย Akash Karthik <notifications@github.com>:
Sent from my iPad

Hi Griffpatch ,

Looks like your search bar sometimes dissapears . I have seen many people writing this in the reviews . I think this needs fixing .
I know some HTML :p
And yes your extension has been copied . #25

**Comment by Akash-Karthik** [comment]
> I found this issue too i think that is made of JavaScript not HTML เมื่อ 10 ก.ย. 2020 6:04 เขียนโดย Akash Karthik <notifications@github.com>: Sent from my iPad Hi Griffpatch , Looks like your search bar sometimes dissapears . I have seen many people writing this in the reviews . I think this needs fixing . I know some HTML :p And yes your extension has been copied . #25 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I know it is made of javascript , i just said i know html

**Comment by Akash-Karthik** [comment]
Closed
