### ISSUE TITLE
When I type "绝对值"(abs in Chinese) in the floating input box and drag out the block, it always return 0

### ISSUE THREAD

**Issue by 570WQL** [griffpatch/Scratch3-Dev-Tools#29]
Note: I am using Version 0.2.4 of you awesome tool in TurboWarp Desktop 0.0.4.

![image](https://user-images.githubusercontent.com/79392947/108616955-47276500-744d-11eb-9abd-5aa262f453a2.png)

Normally it should work like this.

![3](https://user-images.githubusercontent.com/79392947/108617030-dd5b8b00-744d-11eb-93de-7bc88b2a5523.gif)

But when I tried to use the Middle-click box to search the block, it turned out "perfectly" at first. Only when I testing my project did I realized that there was something wrong with the block.

![4](https://user-images.githubusercontent.com/79392947/108617032-dfbde500-744d-11eb-8e7f-d2f37182891c.gif)

It will always return 0.

_(Poor English T_T)_

**Comment by 570WQL** [comment]
It's OK now. I have updated my TurboWarp to v0.1.0 and it works now.

**Comment by griffpatch** [comment]
Great! I did some extra dev since then to do with these kind of blocks -
glad that it fixed it yay
