### ISSUE TITLE
Find Input looks weird

### ISSUE THREAD

**Issue by Sheshank-s** [griffpatch/Scratch3-Dev-Tools#7]
![image](https://user-images.githubusercontent.com/11379161/65149447-f51c1d80-d9d6-11e9-9a3f-0eb3dab64174.png)
MacOs Mojave, using developer version of your extension

**Comment by ghost** [comment]
Look at my PR #2

**Comment by griffpatch** [comment]
Hey there, I pulled your changes, but wanted somewhat of a different look and feel. Can you test my latest changes to see if they still look off in your browser? They are supposed to follow the style of the attributes drop down to some degree.

**Comment by Sheshank-s** [comment]
@griffpatch It looks good on Ubuntu 16.04. I'll test on the Mac that it wasn't looking right on in a few hours

**Comment by griffpatch** [comment]
Did you manage to test this on Ubuntu? Thanks

**Comment by Sheshank-s** [comment]
Oh sorry, I forgot to tell you, yes I did and it works great!
